### PR TITLE
issue/70 Allow global tutor config

### LINKED ISSUE #70: Course level tutor config
Would it be possible to be able to define a global config for tutor?

Currently, if I want to change the feedback type in a course globally I would be required to add the `"_type": "inline"` config to each question component.

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #70 

### Added
* `_isInherited = true` to component config
* course.json defaults

### CODE REVIEW

**Comment by guywillis** [comment]
Yes, I think so

**Review by guywillis — APPROVED** [review]
Tested on MacBook Pro Monterey v12.4 Chrome with global config plus component override 👍

**Review by guywillis — APPROVED** [review]
👍

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Pull request merged**
