### PR TITLE
Fixes page jump on tutor show and hide

### PR DESCRIPTION
**Pull request by oliverfoster**
@zenduo  belal identified an ios issue with the tutor whereby it jumps up and down the page on tutor open + close.

### CODE REVIEW

**Comment by brian-learningpool** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by belal-almassri-spongeuk** [comment]
Hi Oliver, thanks for working on this, this problem it seems to be fixed on Android devices, but the issue still exist in tablet and iPhone devices.

**Comment by oliverfoster** [comment]
That's odd, I was working with an iPad whilst fixing this bug.. let me find the os number..

**Comment by belal-almassri-spongeuk** [comment]
The test performed on IPad model MC775C/A, when you submit MCQ answer the page scrolls.

**Comment by belal-almassri-spongeuk** [comment]
+1
Thanks Ollie, the fix on the following merge seems to solve this problem. 

https://github.com/adaptlearning/adapt_framework/pull/582/files

**Pull request merged**
