### PR TITLE
Fix: Incorrect return early logic in onButtonsViewPostRender (fixes #102)

### LINKED ISSUE #102: Tutor "inline" fails to modify buttons
### Subject of the issue/enhancement/features
When Tutor's feedback is set to '"_type": "inline"', Tutor's [README](https://github.com/adaptlearning/adapt-contrib-tutor/blob/ffc89fc8babd3f868a646d2303550ed4e70dd81c/README.md?plain=1#L24) is not in sync with its actual behaviour. I don't know which is correct.

### My environment
* FW v5.31.17
* Tutor v4.5.8
* MCQ v7.3.11
* Chrome desktop

### Steps to reproduce
1. Install Tutor in the demo course installed with the FW.
2. Add the following code to course.json:
```JSON
"_tutor": {
        "_type": "notify",
        "_classes": "",
        "_hasNotifyBottomButton": false,
        "_button": {
            "text": "{{_globals._extensions._tutor.hideFeedback}}",
            "ariaLabel": "{{_globals._extensions._tutor.hideFeedback}}"
        }
},
```
3. Add the following code to the first MCQ ("_id": "c-60"):
```JSON
"_tutor": {
        "_isInherited": false,
        "_type": "inline",
        "_classes": "",
        "_hasNotifyBottomButton": false,
        "_button": {
            "text": "{{_globals._extensions._tutor.hideFeedback}}",
            "ariaLabel": "{{_globals._extensions._tutor.hideFeedback}}"
        }
},
```
4. Run course and submit a selection of the MCQ--correct or incorrect, doesn't matter.

### Expected behaviour
According to the  [README](https://github.com/adaptlearning/adapt-contrib-tutor/blob/ffc89fc8babd3f868a646d2303550ed4e70dd81c/README.md?plain=1#L24), I should expect that "inline" will modify the buttons, hiding `btn__feedback` and adding the `is-full-width` class to `btn__action`. I expect this to cause the "Show correct answer" button to become full-width and to cause the "Show feedback" button to disappear.

### Actual behaviour
Inline feedback appears below the component, but the buttons remain unmodified as in the following pic. No new classes are added to the buttons.
image
While the "Show feedback" label is meaningless since the feedback is already displayed, at least the button remains disabled.

I find this actual behaviour regardless of choosing a correct or incorrect option and whether the `_tutor` config is included or not in course.json.

### PR DESCRIPTION
**Pull request by joe-allen-89**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)
#102 

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* Incorrect return early logic in onButtonsViewPostRender #102

### CODE REVIEW

**Review by eleanor-heath — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by chucklorenz — COMMENTED** [review]
'.asString' appears on line 23 as part of getTutorType().
Is it more appropriate to remove it from line 23 rather than add it again in line 40?

**Comment by joe-allen-89** [comment]
> '.asString' appears on line 23 as part of getTutorType(). Is it more appropriate to remove it from line 23 rather than add it again in line 40?

Good point @chucklorenz, it does look cleaner without. Also removed from line 31.

**Review by chucklorenz — APPROVED** [review]
Works as intended

**Review by eleanor-heath — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Pull request merged**
