### PR TITLE
Fix: Do not show notify on return

### LINKED ISSUE #94: Question component feedback popups opening up on page load
### Subject of the issue/enhancement/features
Question component with tutor extension, feedback popups open automatically if you leave the page that contains a completed question and navigate back to it. 

### Your environment
* adapt-framwork - v5.31.6
* Browser - Chrome, Edge
* OS - Windows
* Extension - adapt-contrib-tutor v4.5.7

### Steps to reproduce
Answer the question and navigate to other page and come back to same question page.. The feedback popup is shown.

### Expected behaviour
If you leave the page that contains a completed question and navigate back to it (this includes going to the menu and then going back to the page), It should not open the feedback popups

### Actual behaviour
Question component feedback popups open automatically if you leave the page that contains a completed question and navigate back to it.

### Screenshots (if you can)
adapt-contrib-tutor_v4 5 7

### LINKED ISSUE #100: Question component notify popup
### Subject of the issue/enhancement/features
Since the latest FW version when the feedback for any question component is viewed, then another page visited and the page with the original question revisited the notify/feedback is automatically displayed.

### Your environment
* version (AT v0.11.1/Framework v5.31.4)
* which browser and its version - all browsers
* device(s) + operating system(s) - MacOS

### Steps to reproduce
Submitted an answer to any question component, viewed feedback. Closed the feedback and the progressed to next page. Revisited previous page with answered question.

### Expected behaviour
After revisiting the page the notify/feedback popup should not be automatically displayed

### Actual behaviour
Feedback/notify is automatically displayed

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #100 
fixes #94 

### Fix
* Incorrect enumeration comparison causing feedback to inadvertently show

### CODE REVIEW

**Review by swashbuck — APPROVED** [review]
👍 

Tested with both "notify" and "inline" Tutor style, and it's working.

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by joe-allen-89 — APPROVED** [review]

**Comment by Dougieladd** [comment]
This is still an issue for feedback items that show in modals. I'm not coder... just trying to find a solution to the problem. Currently, I have a bunch of MCQ's with feedback (showing in modals). After answering each question, on return to the page, all of the modal feedback windows are still showing.

**Comment by Dougieladd** [comment]
I have version 4.5.8

**Comment by oliverfoster** [comment]
@Dougieladd 

I need to know how tutor is configured on your course.json and/or on your questions.
Some screen shots would be good also.

**Comment by Dougieladd** [comment]
Thanks... yeah I noticed "INLINE" in the code... but this is not possible for the course I'm doing... What do you need from me exactly? I can show you the issue I see (with modals), but what specifically would you like from me? And thank you for your swift reply... that's very helpful.

**Comment by Dougieladd** [comment]
This is how the MCQ's look... (There's 8 of them).
image

And this is the result on returning to the page... I've closed a few of them so you can see they are all on top of each other... 
image

Let me know if there's something specific you'd like from me... I'm using the authoring tool. And these shots are on PREVIEW... but the same thing happens when I publish and test on SCORMCLOUD or our LMS

**Comment by oliverfoster** [comment]
Can you export the course and send over the zip?

**Comment by Dougieladd** [comment]
I'm not sure I'd be allowed to do that... as it's in build. I've not tried the force rebuild though. I can try that. Are there any files in the published zip I could share?

**Comment by oliverfoster** [comment]
bug

This is a standard vanilla course.

**Comment by Dougieladd** [comment]
We updated the framework to the latest version last week (or the week before) and I updated the plugin on Monday.

**Comment by Dougieladd** [comment]
Hi Oliver, the force rebuild seems to have done the trick for me. You're a genius! I'm just checking with other members of the team (they're working on other client courses with the same issue) to see if it has sorted them out too. But it looks good so far. Thank you for your swift reply and help.

**Comment by Dougieladd** [comment]
Thanks to you! 🙂
________________________________

**Pull request merged**
